name: Trial Plugin
version: 1
author: Cilantro
main: me.cilantro.trialplugin.Trial
api-version: 1.8.8
commands:
  players:
    description: Tells player the players on the server
    usage: /<command>
    aliases: [online]
  tpall:
    description: Tps all player to users location
    usage: /<command>
  smite:
    description: Strikes all with lightning
    usage: /<command>
    aliases:
      - smiteall